---
- hosts: all
  become: true
  vars:
    interface: eth0
    motd: |
      curl -sSL https://install.pi-hole.net | bash
      OR
      sudo bash basic-install.sh --unattended
      http://{{ hostvars[inventory_hostname]['ansible_%s'| format(interface)].ipv4.address }}/admin
      sudo qrencode -t ansiutf8 < /etc/wireguard/client.conf

  tasks:
    - name: Install repos
      include: 'repo.yml'

    - name: Install deps
      include: 'deps.yml'

    # Otherwise the webserver doesn't work in centos/rhel
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install deps
      include: 'pihole.yml'

    - name: Copy using inline content
      copy:
        content: "{{ motd }}"
        dest: /etc/motd

    - name: Install wireguard
      include: 'wireguard.yml'


# TODO ALles per OS in een block ipv losse WHEN statements
# TODO split-tunnel mogelijk maken
# TODO user PI disablen (securen) na rpi installer
# FIXME default route deleten is vast niet zo'n goed idee
# when if [ "$(sudo grubby --default-kernel | sed 's/^[^-]*-//')" != "$(uname -r)" ] ; then echo anders; else echo same; fi
